#!/usr/bin/env bash

set -euo pipefail

AI_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$AI_DIR")"
RULES_DIR="$AI_DIR/rules"
SKILLS_DIR="$AI_DIR/skills"
REVIEW_AGENTS_DIR="$AI_DIR/agents"
META_DIR="$AI_DIR/meta"

GENERATED_HEADER="<!-- Generated by .ai/sync.sh. Edit files in .ai/ and re-run sync.sh. -->"
GENERATED_TOML_HEADER="# Generated by .ai/sync.sh. Edit files in .ai/ and re-run sync.sh."

log() {
  echo "  $*"
}

section() {
  echo
  echo "> $*"
}

read_meta() {
  local file="$1"
  local key="$2"

  grep -E "^${key}:" "$file" 2>/dev/null \
    | head -1 \
    | sed -E "s/^${key}:[[:space:]]*[\"']?([^\"']*)[\"']?[[:space:]]*/\1/"
}

read_agent_meta() {
  local file="$1"
  local key="$2"

  awk -v key="$key" '
    NR == 1 && $0 == "---" { in_meta = 1; next }
    in_meta && $0 == "---" { exit }
    in_meta && index($0, key ":") == 1 {
      sub("^[^:]+:[[:space:]]*", "")
      print
      exit
    }
  ' "$file" \
    | sed -E 's/^[[:space:]]*//; s/[[:space:]]*$//; s/^"//; s/"$//'
}

agent_body() {
  local file="$1"

  awk '
    NR == 1 && $0 == "---" { in_meta = 1; next }
    in_meta && $0 == "---" { in_body = 1; next }
    in_body { print }
  ' "$file"
}

codex_agent_name() {
  local file="$1"
  local name

  name="$(read_agent_meta "$file" "codexName")"
  if [ -z "$name" ]; then
    name="$(read_agent_meta "$file" "name" | tr '-' '_')"
  fi
  echo "$name"
}

write_codex_agent() {
  local source_file="$1"
  local output_file="$2"
  local name
  local description
  local model
  local reasoning_effort
  local sandbox_mode
  local nicknames

  name="$(codex_agent_name "$source_file")"
  description="$(read_agent_meta "$source_file" "description")"
  model="$(read_agent_meta "$source_file" "codexModel")"
  reasoning_effort="$(read_agent_meta "$source_file" "codexReasoningEffort")"
  sandbox_mode="$(read_agent_meta "$source_file" "sandboxMode")"
  nicknames="$(read_agent_meta "$source_file" "nicknames")"

  [ -n "$model" ] || model="gpt-5.4"
  [ -n "$reasoning_effort" ] || reasoning_effort="high"
  [ -n "$sandbox_mode" ] || sandbox_mode="read-only"
  [ -n "$nicknames" ] || nicknames="[]"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "$GENERATED_TOML_HEADER"
    echo "name = \"${name}\""
    echo "description = \"${description}\""
    echo "model = \"${model}\""
    echo "model_reasoning_effort = \"${reasoning_effort}\""
    echo "sandbox_mode = \"${sandbox_mode}\""
    echo "nickname_candidates = ${nicknames}"
    echo "developer_instructions = \"\"\""
    agent_body "$source_file"
    echo "\"\"\""
  } > "$output_file"
}

write_markdown_agent() {
  local source_file="$1"
  local output_file="$2"
  local tool_kind="$3"
  local name
  local description

  name="$(read_agent_meta "$source_file" "name")"
  description="$(read_agent_meta "$source_file" "description")"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "---"
    echo "name: ${name}"
    echo "description: ${description}"
    case "$tool_kind" in
      claude)
        echo "tools: Read, Grep, Glob"
        echo "model: inherit"
        ;;
      gemini)
        echo "kind: local"
        echo "tools:"
        echo "  - read_file"
        echo "  - grep_search"
        echo "model: inherit"
        echo "temperature: 0.2"
        echo "max_turns: 30"
        ;;
    esac
    echo "---"
    echo
    echo "$GENERATED_HEADER"
    echo
    agent_body "$source_file"
  } > "$output_file"
}

build_index() {
  echo "$GENERATED_HEADER"
  echo

  if [ -f "$AI_DIR/project-guidance.md" ]; then
    cat "$AI_DIR/project-guidance.md"
    echo
    echo "---"
    echo
  fi

  echo "## AI Rules"
  echo
  echo "Read the relevant rule files from \`.ai/rules/\` when the task matches their description."
  echo

  local has_rules="false"
  for rule_file in "$RULES_DIR"/*.md; do
    [ -f "$rule_file" ] || continue
    local name
    local meta_file
    local description
    name="$(basename "$rule_file" .md)"
    meta_file="$META_DIR/${name}.yaml"
    description="Repository-specific rule"
    if [ -f "$meta_file" ]; then
      description="$(read_meta "$meta_file" "description")"
      [ -n "$description" ] || description="Repository-specific rule"
    fi
    echo "- **${name}**: ${description} (read \`.ai/rules/${name}.md\`)"
    has_rules="true"
  done

  if [ "$has_rules" = "false" ]; then
    echo "- No project-specific rules are defined. Use the project skills below for on-demand guidance."
  fi

  echo
  echo "## AI Skills"
  echo
  echo "Read the relevant skill file from \`.ai/skills/\` when the task matches its description."
  echo

  local has_skills="false"
  for skill_path in "$SKILLS_DIR"/*; do
    [ -d "$skill_path" ] || continue
    local name
    local meta_file
    local description
    name="$(basename "$skill_path")"
    meta_file="$META_DIR/${name}.yaml"
    description="Repository-specific skill"
    if [ -f "$meta_file" ]; then
      description="$(read_meta "$meta_file" "description")"
      [ -n "$description" ] || description="Repository-specific skill"
    fi
    echo "- **${name}**: ${description} (read \`.ai/skills/${name}/SKILL.md\`)"
    has_skills="true"
  done

  if [ "$has_skills" = "false" ]; then
    echo "- No project-specific skills are defined yet. Add them under \`.ai/skills/<name>/SKILL.md\`."
  fi

  echo
  echo "## AI Review Agents"
  echo
  echo "Reusable review subagent definitions live in \`.ai/agents/\` and are generated into platform-specific agent formats by \`.ai/sync.sh\`."
  echo

  for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    local name
    local description
    name="$(read_agent_meta "$agent_file" "name")"
    description="$(read_agent_meta "$agent_file" "description")"
    echo "- **${name}**: ${description} (source: \`.ai/agents/$(basename "$agent_file")\`)"
  done
}

write_with_header() {
  local source_file="$1"
  local output_file="$2"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "$GENERATED_HEADER"
    echo
    cat "$source_file"
  } > "$output_file"
}

can_write_dir() {
  local dir="$1"
  local tmp_file

  mkdir -p "$dir" 2>/dev/null || return 1
  tmp_file="$(mktemp "$dir/.sync-test.XXXXXX" 2>/dev/null)" || return 1
  rm -f "$tmp_file"
}

clear_generated_rule_files() {
  local dir="$1"

  mkdir -p "$dir"
  find "$dir" -maxdepth 1 -type f \( -name "*.md" -o -name "*.mdc" \) -delete
}

copy_skill_dir() {
  local skill_dir="$1"
  local output_dir="$2"

  mkdir -p "$output_dir"
  cp -R "$skill_dir"/. "$output_dir"/
}

section "Cursor"

mkdir -p "$ROOT_DIR/.cursor/rules" "$ROOT_DIR/.cursor/skills" "$ROOT_DIR/.cursor/agents"
clear_generated_rule_files "$ROOT_DIR/.cursor/rules"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  meta_file="$META_DIR/${name}.yaml"
  description="Repository-specific rule"
  always_apply="false"

  if [ -f "$meta_file" ]; then
    description="$(read_meta "$meta_file" "description")"
    always_apply="$(read_meta "$meta_file" "alwaysApply")"
    [ -n "$description" ] || description="Repository-specific rule"
    [ -n "$always_apply" ] || always_apply="false"
  fi

  out="$ROOT_DIR/.cursor/rules/${name}.mdc"
  {
    echo "$GENERATED_HEADER"
    echo "---"
    echo "description: ${description}"
    echo "alwaysApply: ${always_apply}"
    echo "---"
    cat "$rule_file"
  } > "$out"
  log "OK    .cursor/rules/${name}.mdc"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  meta_file="$META_DIR/${name}.yaml"
  skill_name="$name"

  if [ -f "$meta_file" ]; then
    skill_name_meta="$(read_meta "$meta_file" "skillName")"
    [ -n "$skill_name_meta" ] && skill_name="$skill_name_meta"
  fi

  copy_skill_dir "$skill_path" "$ROOT_DIR/.cursor/skills/${skill_name}"
  log "OK    .cursor/skills/${skill_name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_markdown_agent "$agent_file" "$ROOT_DIR/.cursor/agents/${name}.md" "cursor"
  log "OK    .cursor/agents/${name}.md"
done

section "Roo"

mkdir -p "$ROOT_DIR/.roo/rules" "$ROOT_DIR/.roo/skills"
clear_generated_rule_files "$ROOT_DIR/.roo/rules"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.roo/rules/${name}.md"
  log "OK    .roo/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.roo/skills/${name}"
  log "OK    .roo/skills/${name}"
done

section "Codex"

build_index > "$ROOT_DIR/AGENTS.md"
log "OK    AGENTS.md"

if can_write_dir "$ROOT_DIR/.codex"; then
  mkdir -p "$ROOT_DIR/.codex/skills" "$ROOT_DIR/.codex/rules" "$ROOT_DIR/.codex/agents"
  clear_generated_rule_files "$ROOT_DIR/.codex/rules"
  build_index > "$ROOT_DIR/.codex/AGENTS.md"
  log "OK    .codex/AGENTS.md"

  for rule_file in "$RULES_DIR"/*.md; do
    [ -f "$rule_file" ] || continue
    name="$(basename "$rule_file" .md)"
    write_with_header "$rule_file" "$ROOT_DIR/.codex/rules/${name}.md"
    log "OK    .codex/rules/${name}.md"
  done

  for skill_path in "$SKILLS_DIR"/*; do
    [ -d "$skill_path" ] || continue
    name="$(basename "$skill_path")"
    copy_skill_dir "$skill_path" "$ROOT_DIR/.codex/skills/${name}"
    log "OK    .codex/skills/${name}"
  done

  for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    name="$(read_agent_meta "$agent_file" "name")"
    write_codex_agent "$agent_file" "$ROOT_DIR/.codex/agents/${name}.toml"
    log "OK    .codex/agents/${name}.toml"
  done
else
  log "SKIP  .codex (directory is not writable in this environment)"
fi

section "Claude"

mkdir -p "$ROOT_DIR/.claude/skills" "$ROOT_DIR/.claude/rules" "$ROOT_DIR/.claude/agents"
clear_generated_rule_files "$ROOT_DIR/.claude/rules"
build_index > "$ROOT_DIR/.claude/CLAUDE.md"
log "OK    .claude/CLAUDE.md"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.claude/rules/${name}.md"
  log "OK    .claude/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.claude/skills/${name}"
  log "OK    .claude/skills/${name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_markdown_agent "$agent_file" "$ROOT_DIR/.claude/agents/${name}.md" "claude"
  log "OK    .claude/agents/${name}.md"
done

section "Gemini"

mkdir -p "$ROOT_DIR/.gemini/skills" "$ROOT_DIR/.gemini/rules" "$ROOT_DIR/.gemini/agents"
clear_generated_rule_files "$ROOT_DIR/.gemini/rules"
build_index > "$ROOT_DIR/.gemini/GEMINI.md"
log "OK    .gemini/GEMINI.md"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.gemini/rules/${name}.md"
  log "OK    .gemini/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.gemini/skills/${name}"
  log "OK    .gemini/skills/${name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_markdown_agent "$agent_file" "$ROOT_DIR/.gemini/agents/${name}.md" "gemini"
  log "OK    .gemini/agents/${name}.md"
done

echo
echo "Done."
