REQUEST_ID_NAME = "request_id"
CORRELATION_ID_NAME = "correlation_id"
TRACEPARENT_NAME = "traceparent"
TRACESTATE_NAME = "tracestate"
SCOPE_TYPE_NAME = "scope_type"
JWT_TOKEN_NAME = "jwt_token"
USER_ID_NAME = "user_id"
